# Generated by Django 2.2.3 on 2021-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingclass',
            options={'ordering': ('-teaching_class_timestamp',)},
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teaching_class_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teaching_class_section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teaching_class_subject',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teaching_class_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
