# Generated by Django 2.2.3 on 2021-02-19 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentApp', '0002_auto_20210220_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingclass',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teaching_class_class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JoinedClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('class_code', models.CharField(max_length=50)),
                ('joined_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.TeachingClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-joining_date',),
            },
        ),
    ]
