# Generated by Django 2.2.3 on 2021-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingclass',
            options={'ordering': ('-class_timestamp',)},
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_author',
            new_name='class_author',
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_class_code',
            new_name='class_class_code',
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_name',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_section',
            new_name='class_section',
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_subject',
            new_name='class_subject',
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='teaching_class_timestamp',
            new_name='class_timestamp',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/img/default_profile.png', null=True, upload_to='profile/img'),
        ),
    ]
