# Generated by Django 2.2.3 on 2021-02-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_auto_20210221_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingclass',
            old_name='class_class_code',
            new_name='class_code',
        ),
    ]
