# Generated by Django 2.2.3 on 2021-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_semester', models.CharField(default='', max_length=20)),
                ('class_course_code', models.CharField(default='', max_length=10)),
                ('class_course_name', models.CharField(default='', max_length=20)),
                ('class_assigned_teacher', models.CharField(default='', max_length=20)),
                ('class_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_no', models.CharField(max_length=10)),
                ('classroom_used_for', models.CharField(default='Theory', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_semester', models.CharField(default='', max_length=20)),
                ('course_type', models.CharField(default='Theory', max_length=10)),
                ('course_code', models.CharField(default='', max_length=15)),
                ('course_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(default='', max_length=30)),
                ('faculty_designation', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(default='', max_length=100)),
                ('notice_description', models.CharField(default='nothing is posted', max_length=5000)),
            ],
        ),
    ]
