# Generated by Django 2.2.3 on 2021-01-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_time',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
    ]
