# Generated by Django 2.2.3 on 2021-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_class_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_classroom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='class_duration',
            field=models.CharField(default='45 min', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_semester',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_designation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
