# Generated by Django 2.2.3 on 2021-02-19 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_auto_20210216_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_assigned_teacher',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_course_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
